// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBxxgxNYR8ytoED3bkwJThSgG4dDFAlmVk',
    appId: '1:526220104670:web:dde76e7f4a62931c43c34f',
    messagingSenderId: '526220104670',
    projectId: 'medinate-e6c37',
    authDomain: 'medinate-e6c37.firebaseapp.com',
    storageBucket: 'medinate-e6c37.appspot.com',
    measurementId: 'G-RLXG8JXX5Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBMa8mnFhTu_MishQdlbFG0VULLyAJvem8',
    appId: '1:526220104670:android:b713f569001925e243c34f',
    messagingSenderId: '526220104670',
    projectId: 'medinate-e6c37',
    storageBucket: 'medinate-e6c37.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAb4NczFVrAk8xAixRhZpiCQ8paw-R-p8A',
    appId: '1:526220104670:ios:db921bb4cbbe145543c34f',
    messagingSenderId: '526220104670',
    projectId: 'medinate-e6c37',
    storageBucket: 'medinate-e6c37.appspot.com',
    iosClientId: '526220104670-ue8ag8ch79i43ig4b9cf2uv0f6fb8qvt.apps.googleusercontent.com',
    iosBundleId: 'com.example.medinate',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAb4NczFVrAk8xAixRhZpiCQ8paw-R-p8A',
    appId: '1:526220104670:ios:db921bb4cbbe145543c34f',
    messagingSenderId: '526220104670',
    projectId: 'medinate-e6c37',
    storageBucket: 'medinate-e6c37.appspot.com',
    iosClientId: '526220104670-ue8ag8ch79i43ig4b9cf2uv0f6fb8qvt.apps.googleusercontent.com',
    iosBundleId: 'com.example.medinate',
  );
}
